name: hashicorp-nomad
version: '0.12.1' 
summary: Nomad is an easy-to-use, flexible, and performant workload orchestrator
description: |
  Nomad enables developers to use declarative infrastructure-as-code for 
  deploying their applications (jobs). Nomad uses bin packing to efficiently 
  schedule jobs and optimize for resource utilization. 
  Nomad is supported on macOS, Windows, and Linux.

grade: stable
confinement: strict
base: core18

architectures:
  - build-on: amd64
    run-on: amd64

parts:
  nomad:
    plugin: dump
    source: https://releases.hashicorp.com/nomad/$SNAPCRAFT_PROJECT_VERSION/nomad_$SNAPCRAFT_PROJECT_VERSION_linux_amd64.zip

apps:
  nomad:
    command: nomad
    plugs:
      - network
      - docker
